import assert from 'node:assert/strict';
import test from 'node:test';

import {
  checkBackendEnv,
  checkFrontendEnv,
  checkMainTrack,
  checkNode,
  checkSeoOutput,
  forbiddenFiles,
  isAbsolutePath,
  unexpectedDistFiles
} from './checks.mjs';

const ORIGIN = 'https://release-check.example.com';
const levels = (results) => results.map((result) => result.level);
const failing = (results) => results.filter((result) => result.level === 'fail').map((result) => result.message);

const goodBackend = {
  NODE_ENV: 'production',
  SERVE_FRONTEND: 'true',
  PORT: '1369',
  HOST: '127.0.0.1',
  TRUST_PROXY_HOPS: '1',
  PUBLIC_ORIGIN: ORIGIN,
  LEAD_STORE: 'file',
  LEAD_STORE_PATH: 'D:\\PDA\\shared\\data\\leads.jsonl',
  CORS_ORIGIN: 'http://localhost:1368',
  LOG_LEVEL: 'info'
};

test('node 22+ is required', () => {
  assert.equal(checkNode('v22.22.2').level, 'pass');
  assert.equal(checkNode('v24.1.0').level, 'pass');
  assert.equal(checkNode('v20.19.0').level, 'fail');
});

test('a correct production backend env passes cleanly', () => {
  assert.deepEqual(failing(checkBackendEnv(goodBackend)), []);
  assert.ok(!levels(checkBackendEnv(goodBackend)).includes('warn'));
});

test('unsafe or incomplete backend env fails loudly', () => {
  const cases = [
    [{ NODE_ENV: 'development' }, /NODE_ENV/],
    [{ SERVE_FRONTEND: 'false' }, /SERVE_FRONTEND/],
    [{ PUBLIC_ORIGIN: '' }, /OWNER DECISION/],
    [{ PUBLIC_ORIGIN: 'http://pdabliss.example.com' }, /public https/],
    [{ PUBLIC_ORIGIN: 'https://localhost' }, /public https/],
    [{ PUBLIC_ORIGIN: 'https://192.168.1.20' }, /public https/],
    [{ PUBLIC_ORIGIN: 'https://site.example.com/app' }, /public https/],
    [{ LEAD_STORE: 'memory' }, /lost on every restart/],
    [{ LEAD_STORE_PATH: './data/leads.jsonl' }, /relative/],
    [{ CORS_ORIGIN: '*' }, /wildcard|"\*"/],
    [{ PORT: 'abc' }, /not a valid port/]
  ];
  for (const [override, pattern] of cases) {
    const messages = failing(checkBackendEnv({ ...goodBackend, ...override }));
    assert.ok(messages.some((message) => pattern.test(message)), `${JSON.stringify(override)} -> ${messages.join(' | ')}`);
  }
});

test('a LAN-reachable bind or odd proxy hop count warns', () => {
  assert.ok(levels(checkBackendEnv({ ...goodBackend, HOST: '0.0.0.0' })).includes('warn'));
  assert.ok(levels(checkBackendEnv({ ...goodBackend, TRUST_PROXY_HOPS: '3' })).includes('warn'));
});

test('absolute paths are recognised on Windows and POSIX', () => {
  for (const path of ['D:\\S2A\\shared\\leads.jsonl', 'C:/data/leads.jsonl', '\\\\nas\\share\\x', '/srv/data']) assert.ok(isAbsolutePath(path), path);
  for (const path of ['./data/leads.jsonl', 'data\\leads.jsonl', 'leads.jsonl']) assert.ok(!isAbsolutePath(path), path);
});

test('frontend origin must exist, be public https and match the backend', () => {
  assert.deepEqual(failing(checkFrontendEnv({ VITE_PUBLIC_ORIGIN: `${ORIGIN}/` }, ORIGIN)), []);
  assert.match(failing(checkFrontendEnv({}, ORIGIN))[0], /OWNER DECISION/);
  assert.match(failing(checkFrontendEnv({ VITE_PUBLIC_ORIGIN: 'https://10.0.0.5' }, ORIGIN))[0], /not a public https/);
  assert.match(failing(checkFrontendEnv({ VITE_PUBLIC_ORIGIN: 'https://other.example.com' }, ORIGIN))[0], /different sites/);
});

test('missing owner audio is provisioning, a tracked track is a source-control failure', () => {
  assert.deepEqual(levels(checkMainTrack({ inPublic: false, inDist: false, tracked: false, distChecked: true })), ['provision']);
  assert.deepEqual(levels(checkMainTrack({ inPublic: true, inDist: true, tracked: false, distChecked: true })), ['pass']);
  assert.ok(levels(checkMainTrack({ inPublic: true, inDist: true, tracked: true, distChecked: true })).includes('fail'));
  assert.ok(levels(checkMainTrack({ inPublic: true, inDist: false, tracked: false, distChecked: true })).includes('fail'));
});

test('raw media, archives, maps, env files and private folders are forbidden in dist', () => {
  const bad = ['images/memories/IMG_0001.HEIC', 'videos/raw.MOV', 'assets/index-abc12345.js.map', 'review-local/sheet.webp', 'media-inbox/a.webp', 'backup.zip', '.env', 'data/leads.jsonl', 'images/drive-2026-09-20/x.webp'];
  const good = ['images/memories/cat-01.webp', 'videos/memories/film-2026.mp4', 'audio/main-track.mp3', 'audio/sfx/.gitkeep', 'images/work/.gitkeep', 'robots.txt'];
  assert.deepEqual(forbiddenFiles([...bad, ...good]), bad);
});

test('dist files must be tracked in public/ or generated by the build', () => {
  const tracked = ['robots.txt', 'site.webmanifest', 'brand/favicon.svg', 'images/memories/cat-01.webp'];
  const dist = [...tracked, 'index.html', 'sitemap.xml', 'assets/index-AbCd1234.js', 'assets/index-AbCd1234.css', 'audio/main-track.mp3', 'audio/sfx/click.mp3', 'images/memories/qa-screenshot.png', 'notes.txt'];
  assert.deepEqual(unexpectedDistFiles(dist, tracked), ['images/memories/qa-screenshot.png', 'notes.txt']);
});

test('SEO output: sitemap on the origin, no private routes, robots and share image wired', () => {
  const robots = `Allow: /\nDisallow: /login\nDisallow: /memory-gate\nDisallow: /workspace\nDisallow: /us\nDisallow: /dev/\nSitemap: ${ORIGIN}/sitemap.xml\n`;
  const sitemap = `<urlset><url><loc>${ORIGIN}/</loc></url><url><loc>${ORIGIN}/en/services</loc></url></urlset>`;
  const indexHtml = `<meta property="og:image" content="${ORIGIN}/brand/og-default.png" />`;
  assert.deepEqual(failing(checkSeoOutput({ origin: ORIGIN, robots, sitemap, indexHtml })), []);

  assert.ok(failing(checkSeoOutput({ origin: ORIGIN, robots, sitemap: null, indexHtml })).some((m) => /sitemap.xml missing/.test(m)));
  assert.ok(failing(checkSeoOutput({ origin: ORIGIN, robots: 'Allow: /', sitemap, indexHtml })).length >= 2);
  const leaky = sitemap.replace('</urlset>', `<url><loc>${ORIGIN}/en/login</loc></url></urlset>`);
  assert.ok(failing(checkSeoOutput({ origin: ORIGIN, robots, sitemap: leaky, indexHtml })).some((m) => /private routes/.test(m)));
  const foreign = sitemap.replace(`${ORIGIN}/en/services`, 'https://elsewhere.example.com/');
  assert.ok(failing(checkSeoOutput({ origin: ORIGIN, robots, sitemap: foreign, indexHtml })).some((m) => /outside/.test(m)));
});
